### ISSUE TITLE
Add/modify to the lucid chart structure

### ISSUE THREAD

**Issue by Meroni-bcg** [Meroni-bcg/Social-Media-Platform#1]
https://lucid.app/lucidchart/4a143e32-5ea6-4fd0-9a40-2461250eb73c/edit?viewport_loc=-616%2C-1565%2C2828%2C1464%2C0_0&invitationId=inv_92f8e10e-def4-4c00-ae2b-10060863cb01

**Comment by KGriffin12** [comment]
Finished Lucid Chart.
